services:

  db:
    image: mariadb:11.4
    hostname: localmariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  ordermanager:
    build: .
    depends_on:
      db:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mariadb://localmariadb:3306/db
      MEILISEARCH_HOST: http://localmelisearch:7700
      REDIS_HOST: localredis

  meilisearch:
    hostname: localmelisearch
    image: getmeili/meilisearch:v1.12
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    healthcheck:
      test: set -o pipefail;curl -fsS http://localhost:7700/health | grep -q '{"status":"available"}'
      retries: 3
      timeout: 5s

  redis:
    hostname: localredis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      REDIS_PORT: 6379
      ALLOW_EMPTY_PASSWORD: yes
