spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/db}
    username: ${DB_USER:user}
    password: ${DB_PWD:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    locations: classpath:db/migrations # the location where flyway should look for migration scripts
    url: ${DB_URL:jdbc:mariadb://localhost:3306/db}
    user: ${DB_USER:user}
    password: ${DB_PWD:password}
    driver: org.mariadb.jdbc.Driver
    validateMigrationNaming: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
meilisearch:
  url: ${MEILISEARCH_HOST:http://localhost:7700}
  apiKey: ${MEILISEARCH_MASTER_KEY:masterKey}
  ordersIndex: orders
  ordersTopic: order-events
