spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://localhost:3306/db}
    username: ${DB_USER:test}
    password: ${DB_PWD:test}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    locations: classpath:db/migrations # the location where flyway should look for migration scripts
    url: ${DB_URL:jdbc:mariadb://localhost:3306/db}
    user: ${DB_USER:test}
    password: ${DB_PWD:test}
    driver: org.mariadb.jdbc.Driver
    validateMigrationNaming: true